/*
 * This source file was generated by the Gradle 'init' task
 */
package fr.oiseaux;

import javax.swing.SwingUtilities;

import fr.oiseaux.controller.ModelController;
import fr.oiseaux.model.BoidsModel;
import fr.oiseaux.model.VicsekModel;
import fr.oiseaux.view.ControlPanel;
import fr.oiseaux.view.MainWindow;
import fr.oiseaux.view.SimulationPanel;

public class App {
  public static void main(String[] args) {
    SwingUtilities.invokeLater(() -> {
      VicsekModel vicsekModel = new VicsekModel(8, 0.0001, 0.23);
      BoidsModel boidsModel = new BoidsModel(8, 0.0001, 0.23);

      SimulationPanel simPanel = new SimulationPanel();
      ControlPanel ctrlPanel = new ControlPanel();
      MainWindow window = new MainWindow(simPanel, ctrlPanel);

      new ModelController(vicsekModel, boidsModel, window, simPanel, ctrlPanel);

      window.setVisible(true);
    });
  }
}
