/*
 * This source file was generated by the Gradle 'init' task
 */
package fr.oiseaux;

import fr.oiseaux.model.SimpleModel;
import fr.oiseaux.view.ControlPanel;
import fr.oiseaux.view.MainWindow;
import fr.oiseaux.view.SimulationPanel;
import fr.oiseaux.controller.ModelController;
import javax.swing.SwingUtilities;
import fr.oiseaux.model.VicsekModel;

public class App {
  public static void main(String[] args) {
    SwingUtilities.invokeLater(() -> {
      VicsekModel model = new VicsekModel(8, 0.0001, 0.23);

      SimulationPanel simPanel = new SimulationPanel(model);
      ControlPanel ctrlPanel = new ControlPanel();
      MainWindow window = new MainWindow(simPanel, ctrlPanel);

      new ModelController(model, simPanel, ctrlPanel);

      window.setVisible(true);
    });
  }
}
